title: "Antonella Basso"
author: "Antonella D. Basso"
description: "She/Her/Ella" # "Made with <b style=\"color: #f45;\">&lt;3</b>", "Brown University, '23"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout
 
show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}
  - {file: "README.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:antonella_basso@brown.edu"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/antonella-basso-347026180/"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/abasso98"}
  - {title: Github, icon: github, url: "https://github.com/antonellabasso"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
